export const environment = {
  production: true,
  secondaryBaseUrl: "https://api.getkexy.com/kexyapi/v1/",
  baseUrl: "https://apiv2.getkexy.com/v2/",
  imageUrl: "https://cdn.getkexy.com/",
  externalAssetUrl: "https://cdn.getkexy.com/KEXY_Connect_assets/",
  siteUrl: "https://client.getkexy.com",
  distributorPortalUrl: "https://client.getkexy.com/distributor/",
  supplierPortalUrl: "https://client.getkexy.com/brand/",
  socketUri: "https://api.getkexy.com:3001",
  mockSocketUri: "https://api.getkexy.com:4001",
  ZONE_ID: 536897,
  GLEAP_KEY: "rEVzmGo71SZyqgf0tYkYa6lOf3YjnzKy",
  RECOMMENDED_DEAL_ZONE_ID: 536898,
  zoneOne: 536897,
  zoneTwo: 536898,
  FIFTY_PERCENT_COUPON_CODE: "FRIENDS50",
  KEXY_MASTER_PASSWORD: "kEXyMaster1287",
  AMATEUR_COUPONS: ["199KEXY24"],
  PRO_COUPONS: ["299KEXY24"],
  LIFETIME_COUPONS: ["FLEXMEKEXY24", 'LIFETIMEMEKEXY24'],
  ADDITIONAL_CREDITS_COUPONS: ["KXY502024", "KXY70CREDITS", "80KXY2024"],
  dripCampaignCreateTutorialUrl: "https://vimeo.com/937954323/803f7f4860?share=copy",
  brandSignupWelcomePageVideoUrl: "https://www.youtube.com/watch?v=Ual9aw-cct0",
  newEmailGenerateApiUrl: "https://owozderf5udwgqcfbplqhdnbyi0oseqb.lambda-url.us-east-1.on.aws/",
  oldConversationEmailGenerateApiUrl: "https://xdkuzewpr6ja5d3p2r6er3ayjm0dyiii.lambda-url.us-east-1.on.aws/",
  dripBulkEmailApiUrl: "https://zs7hmhpqo7aynkshbcm563todm0bwlvh.lambda-url.us-east-1.on.aws/",
  dripFollowUpEmailApiUrl: "https://wejj7s3ropawmuvxgqwthj4slm0sqcrr.lambda-url.us-east-1.on.aws/",
};
